In [10]:
import pandas as pd

In [11]:
import matplotlib.pyplot as plt

In [12]:
data = pd.read_csv("smart_city_cloud_usage.csv")

In [13]:
data.head()

,Date,Department,Service_Type,Application,Region,Usage_Hours,Cost_INR
0,2026-01-01,Traffic,Compute,Traffic Signal AI,India-North,222,4038
1,2026-01-01,Surveillance,Database,Surveillance DB,India-East,203,3130
2,2026-01-01,Healthcare,Storage,Patient Data Backup,India-West,337,1805
3,2026-01-01,Water,Storage,Water Records Backup,India-East,270,2184
4,2026-01-01,Transport,Networking,Transport Sensors,India-West,168,1374

In [14]:
data.columns

Index(['Date', 'Department', 'Service_Type', 'Application', 'Region',
       'Usage_Hours', 'Cost_INR'],
      dtype='str')

In [15]:
data.count()

Date            1465
Department      1465
Service_Type    1465
Application     1465
Region          1465
Usage_Hours     1465
Cost_INR        1465
dtype: int64

In [16]:
data.shape

(1465, 7)

In [17]:
data.dtypes

Date              str
Department        str
Service_Type      str
Application       str
Region            str
Usage_Hours     int64
Cost_INR        int64
dtype: object

In [18]:
data.describe()

       Usage_Hours     Cost_INR
count  1465.000000  1465.000000
mean    231.632765  2674.238908
std      75.028375  1198.478360
min     120.000000   900.000000
25%     178.000000  1480.000000
50%     214.000000  3045.000000
75%     267.000000  3762.000000
max     420.000000  4886.000000

In [19]:
data.groupby('Service_Type')['Cost_INR'].sum().reset_index()

  Service_Type  Cost_INR
0      Compute   1439964
1     Database   1395206
2   Networking    445622
3      Storage    636968

In [20]:
data.groupby('Department')['Cost_INR'].sum().reset_index()

     Department  Cost_INR
0   Electricity    626387
1    Healthcare    654960
2  Surveillance    617846
3       Traffic    697932
4     Transport    646552
5         Water    674083

In [22]:
data['Date']=pd.to_datetime(data['Date'])
data['Month']=data['Date'].dt.month

data.groupby(['Service_Type','Month'])['Cost_INR'].sum().reset_index()

   Service_Type  Month  Cost_INR
0       Compute      1    146035
1       Compute      2     99293
2       Compute      3    133780
3       Compute      4    146834
4       Compute      5    147009
5       Compute      6    104091
6       Compute      7    116464
7       Compute      8    112366
8       Compute      9    101146
9       Compute     10    105216
10      Compute     11    105241
11      Compute     12    122489
12     Database      1     99443
13     Database      2    128990
14     Database      3     91897
15     Database      4     80649
16     Database      5     92736
17     Database      6     95719
18     Database      7    129878
19     Database      8    143925
20     Database      9    162222
21     Database     10    142340
22     Database     11    116302
23     Database     12    111105
24   Networking      1     41878
25   Networking      2     31817
26   Networking      3     32178
27   Networking      4     36500
28   Networking      5     37037
29   Networking      6     39895
30   Networking      7     36268
31   Networking      8     49824
32   Networking      9     34500
33   Networking     10     43213
34   Networking     11     27075
35   Networking     12     35437
36      Storage      1     51415
37      Storage      2     45820
38      Storage      3     59110
39      Storage      4     49617
40      Storage      5     53975
41      Storage      6     53141
42      Storage      7     42908
43      Storage      8     46968
44      Storage      9     46067
45      Storage     10     51714
46      Storage     11     72986
47      Storage     12     63247